stages:
  - build
  - deploy

Build:
  image: python:latest
  stage: build
  artifacts:
    untracked: true
  script: 
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py collectstatic --no-input

Deployment:
  image: ruby:2.4
  stage: deploy
  dependencies: 
    - Build
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    - export HEROKU_API_KEY=$HEROKU_API_KEY
    - heroku run --app $HEROKU_APP_NAME python manage.py migrate
  environment:
    name: production
    url: $HEROKU_APP_HOST
  only:
    - master
