# Generated by Django 3.2.8 on 2021-11-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminder_Makan_Minum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makanminum',
            name='tanggal',
        ),
        migrations.AlterField(
            model_name='makanminum',
            name='jadwalMakan',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
