# Generated by Django 3.2.8 on 2021-11-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reminder_Makan_Minum', '0002_auto_20211104_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makanminum',
            old_name='hari',
            new_name='tanggal',
        ),
    ]
