# Generated by Django 3.2.7 on 2021-10-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminder_Aktivitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.TimeField(),
        ),
    ]
