# Generated by Django 3.2.7 on 2021-11-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminder_Aktivitas', '0003_alter_activity_aktivitas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='time',
        ),
        migrations.AlterField(
            model_name='activity',
            name='aktivitas',
            field=models.TextField(),
        ),
    ]
