# Generated by Django 3.2.7 on 2021-11-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminder_Aktivitas', '0004_auto_20211104_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('waktuawal', models.DateTimeField()),
                ('waktuakhir', models.DateTimeField()),
                ('event', models.TextField()),
            ],
        ),
    ]
