# Generated by Django 3.2.7 on 2021-11-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminder_Aktivitas', '0008_rename_date_activity_hari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='hari',
            field=models.CharField(max_length=30),
        ),
    ]
