# Generated by Django 3.2.7 on 2021-11-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reminder_Aktivitas', '0009_alter_activity_hari'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='hari',
            new_name='date',
        ),
    ]
