# Generated by Django 3.2.7 on 2021-10-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='healthRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=30)),
                ('tanggal', models.DateField()),
                ('suhu', models.CharField(max_length=30)),
                ('sistolik', models.CharField(max_length=30)),
                ('diastolik', models.CharField(max_length=30)),
                ('jantung', models.CharField(max_length=30)),
                ('saturasi', models.CharField(max_length=30)),
            ],
        ),
    ]
