# Generated by Django 3.2.7 on 2021-10-27 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SWABrecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.now)),
                ('hasil', models.CharField(max_length=30)),
                ('ctValue', models.CharField(max_length=30)),
            ],
        ),
    ]
