# Generated by Django 3.2.7 on 2021-10-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.IntegerField(max_length=2)),
                ('tanggal', models.DateField()),
                ('is_demam', models.BooleanField(default=False, verbose_name='Demam')),
                ('is_batuk', models.BooleanField(default=False, verbose_name='Batuk')),
                ('is_kelelahan', models.BooleanField(default=False, verbose_name='Kelelahan')),
                ('is_penciuman', models.BooleanField(default=False, verbose_name='Kehilangan Penciuman')),
                ('curhat', models.CharField(max_length=100)),
            ],
        ),
    ]
