# Generated by Django 3.2.7 on 2021-10-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Daily_Journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='hari',
            field=models.CharField(max_length=2),
        ),
    ]
